### ISSUE TITLE
b0RemoteApiServer crashes when started.

### ISSUE THREAD

**Issue by alvimpaulo** [CoppeliaRobotics/simExtB0#2]
This seems to be caused by the non-existence of function " simB0.pingResolver()" with this plugin.
when I write "simB0" on the lua console within the simulator (Version 4.1.0), the result i get is
> simB0
{
        call="<FUNCTION 0x7f18d0020bb0>",
        cleanup="<FUNCTION 0x7f18d003d760>",
        cleanupSocket="<FUNCTION 0x7f18d0020240>",
        create="<FUNCTION 0x7f18d003e210>",
        createPublisher="<FUNCTION 0x7f18d00202e0>",
        createServiceClient="<FUNCTION 0x7f18d0020b10>",
        createServiceServer="<FUNCTION 0x7f18d0020cf0>",
        createSubscriber="<FUNCTION 0x7f18d00209d0>",
        destroy="<FUNCTION 0x7f18d001fe80>",
        destroyPublisher="<FUNCTION 0x7f18d0020930>",
        destroyServiceClient="<FUNCTION 0x7f18d0020c50>",
        destroyServiceServer="<FUNCTION 0x7f18d0020d90>",
        destroySubscriber="<FUNCTION 0x7f18d0020a70>",
        getHandles="<FUNCTION 0x7f18d00479f0>",
        init="<FUNCTION 0x7f18d003d620>",
        initSocket="<FUNCTION 0x7f18d001ff20>",
        nodeCleanup="<FUNCTION 0x7f18d00a7e60>",
        nodeCreate="<FUNCTION 0x7f18d00a6f70>",
        nodeDestroy="<FUNCTION 0x7f18d00a8260>",
        nodeInit="<FUNCTION 0x7f18d00a7660>",
        nodeSetAnnounceTimeout="<FUNCTION 0x7f18d00a7250>",
        nodeSpin="<FUNCTION 0x7f18d003e130>",
        nodeSpinOnce="<FUNCTION 0x7f18d00a7a60>",
        pingResolver="<FUNCTION 0x7f18d003e1d0>",
        pollSocket="<FUNCTION 0x7f18d0020060>",
        publish="<FUNCTION 0x7f18d0020380>",
        publisherCreate="<FUNCTION 0x7f18d00aa360>",
        publisherDestroy="<FUNCTION 0x7f18d00aab80>",
        publisherPublish="<FUNCTION 0x7f18d00aa770>",
        readSocket="<FUNCTION 0x7f18d0020100>",
        renamedFunction="<FUNCTION 0x7f18d003e1a0>",
        serviceClientCall="<FUNCTION 0x7f18d003aa10>",
        serviceClientCreate="<FUNCTION 0x7f18d0044f50>",
        serviceClientDestroy="<FUNCTION 0x7f18d0041030>",
        serviceServerCreate="<FUNCTION 0x7f18d006b4b0>",
        serviceServerDestroy="<FUNCTION 0x7f18d00636f0>",
        setAnnounceTimeout="<FUNCTION 0x7f18d003e2b0>",
        setCompression="<FUNCTION 0x7f18d0020e30>",
        setSocketOption="<FUNCTION 0x7f18d003f670>",
        socketCleanup="<FUNCTION 0x7f18d00a9f60>",
        socketInit="<FUNCTION 0x7f18d0020420>",
        socketPoll="<FUNCTION 0x7f18d00a9360>",
        socketRead="<FUNCTION 0x7f18d00a9760>",
        socketSetCompression="<FUNCTION 0x7f18d0044c90>",
        socketSetOption="<FUNCTION 0x7f18d005d590>",
        socketSpinOnce="<FUNCTION 0x7f18d0020820>",
        socketWrite="<FUNCTION 0x7f18d00a9b60>",
        spinOnce="<FUNCTION 0x7f18d003d6c0>",
        spinOnceSocket="<FUNCTION 0x7f18d001ffc0>",
        subscriberCreate="<FUNCTION 0x7f18d00aaf90>",
        subscriberDestroy="<FUNCTION 0x7f18d00479b0>",
        writeSocket="<FUNCTION 0x7f18d00201a0>"
    }

on a computer running manjaro, which i did not need to recompile this plugin.
However, when i run the same command within another machine running Ubuntu 20.04, I get the following result:

simB0
{
        getHandles="<FUNCTION 0x7f3b7c0655b0>",
        nodeCleanup="<FUNCTION 0x7f3b7c055ea0>",
        nodeCreate="<FUNCTION 0x7f3b7c03af40>",
        nodeDestroy="<FUNCTION 0x7f3b7c06ead0>",
        nodeInit="<FUNCTION 0x7f3b7c05e400>",
        nodeSetAnnounceTimeout="<FUNCTION 0x7f3b7c059370>",
        nodeSpinOnce="<FUNCTION 0x7f3b7c0425d0>",
        publisherCreate="<FUNCTION 0x7f3b7c039ea0>",
        publisherDestroy="<FUNCTION 0x7f3b7c042dc0>",
        publisherPublish="<FUNCTION 0x7f3b7c059330>",
        serviceClientCall="<FUNCTION 0x7f3b7c056e70>",
        serviceClientCreate="<FUNCTION 0x7f3b7c0320e0>",
        serviceClientDestroy="<FUNCTION 0x7f3b7c06a830>",
        serviceServerCreate="<FUNCTION 0x7f3b7c065df0>",
        serviceServerDestroy="<FUNCTION 0x7f3b7c036380>",
        socketCleanup="<FUNCTION 0x7f3b7c04b730>",
        socketInit="<FUNCTION 0x7f3b7c05ed70>",
        socketPoll="<FUNCTION 0x7f3b7c04b6f0>",
        socketRead="<FUNCTION 0x7f3b7c059010>",
        socketSetCompression="<FUNCTION 0x7f3b7c023690>",
        socketSetOption="<FUNCTION 0x7f3b7c052790>",
        socketSpinOnce="<FUNCTION 0x7f3b7c06cbe0>",
        socketWrite="<FUNCTION 0x7f3b7c057c60>",
        subscriberCreate="<FUNCTION 0x7f3b7c062e50>",
        subscriberDestroy="<FUNCTION 0x7f3b7c054bc0>"
    }

Which does not contain this function. 
This one I had to recompile this plugin to be able to run it. Maybe I am doing something wrong in the compilation?

**Comment by fferri** [comment]
Fixed in the new releases. Please reopen if this is still an issue.
